dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "7"
cache:
  yarn: true
script:
  - set -e
  - yarn lint
  - GEN_TESTS_QTY=40 yarn test test/token/QiibeeToken.js test/crowdsale/Crowdsale.js test/crowdsaleCrowdsaleGenTest.js test/presale/Presale.js test/presale/PresaleGenTest.js test/presale/PresaleStandardTest.js test/WhitelistedCrowdsale.js
after_script:
  - yarn run coveralls
