dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "7"
cache:
  yarn: true
script:
  - set -e
  - yarn lint
  - GEN_TESTS_QTY=40 yarn test test/presale/*
  - GEN_TESTS_QTY=40 yarn test test/crowdsale/*
  - GEN_TESTS_QTY=40 yarn test test/tokeen/*
  - yarn test test/WhitelistedCrowdsale.js

after_script:
  - yarn run coveralls
