dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "7"
cache:
  yarn: true
script:
  - set -e
  - yarn lint
  - GEN_TESTS_QTY=40 yarn test test/token/* test/crowdsale/* test/presale/* test/Crowdsale.js test/WhitelistedCrowdsale.js
after_script:
  - yarn run coveralls
